Update `@lxcat/app` container build
Now uses `bun` to build the app and uses a multi-stage
build to produce a small production image.
Add `.turbo` directory to `.dockerignore` to avoid using
cached builds.

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -2,40 +2,49 @@
 # SPDX-License-Identifier: AGPL-3.0-or-later
 
 # Install dependencies only when needed
-FROM node:24-alpine AS deps
+FROM oven/bun:1-alpine AS base
 
-# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
-RUN apk add --no-cache libc6-compat git rust cargo
-# Enable corepack for pnpm version management.
-RUN corepack enable
+# Use a multi-stage build to keep the release image small
+FROM base AS build
 
-WORKDIR /code
+RUN apk add --no-cache libc6-compat curl build-base
+
+# Install rust
+RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
+ENV PATH="/root/.cargo/bin:${PATH}"
+
+WORKDIR /build
 COPY . .
-RUN bun install --frozen-lockfile
 
-# Next.js collects completely anonymous telemetry data about general usage.
-# Learn more here: https://nextjs.org/telemetry
-# Uncomment the following line in case you want to disable telemetry during the build.
+# TODO: This command currently "fails" with exit code 1 even though packages
+#       install successfully. The `|| :` statement swallows the exit code.
+#       Remove once this is no longer a problem.
+RUN bun install --frozen-lockfile || :
+
+# Uncomment the following line to disable telemetry during the build.
 # ENV NEXT_TELEMETRY_DISABLED 1
+
+# Build a standalone application
+ENV NEXT_PRIVATE_STANDALONE=true
+
+# Set production environment
+ENV NODE_ENV=production
+ENV LXCAT_BUILD_ENV=production
 
 RUN bun run build --no-cache
 
 # Production image, copy all the files and run next
-WORKDIR /code/app
+FROM base AS release
 
-ENV NODE_ENV production
-ENV LXCAT_BUILD_ENV production
-# Uncomment the following line in case you want to disable telemetry during runtime.
+# Uncomment the following line to disable telemetry during runtime.
 # ENV NEXT_TELEMETRY_DISABLED 1
-
-RUN addgroup --system --gid 1001 nodejs
-RUN adduser --system --uid 1001 nextjs
-RUN chown -R nextjs /code/app/.next
-
-USER nextjs
+ 
+COPY --from=build /build/app/.next/standalone .
+COPY --from=build /build/app/.next/static ./app/.next/static
+COPY --from=build /build/app/public ./app/public
 
 EXPOSE 3000
 
-ENV PORT 3000
+ENV PORT=3000
 
-CMD ["bun", "start"]
+CMD ["bun", "app/server.js"]
